# -*- coding: utf-8 -*-
"""Pesquisa de Avaliação.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/139HUpHjJnfYbFUbs6cdTtc3C5LdN8GHv

# Análise dos Microdados do ENADE 2021

Autor: Michel Gomes de Andrade

Processo seletivo : Desenvolvimento de Tecnologia - Estágiario em Pesquisa de Avaliação

**0 - Preparação do ambiente e carga dos dados analisados**
"""

import pandas as pd

"""Os dados utilizados nesta análise correspondem aos microdados do ENADE 2021,
disponibilizados pelo INEP no portal de dados abertos.

Para reproduzir os resultados, é necessário baixar o arquivo
`microdados_enade_2021.txt` e realizar o upload manual no Google Colab
utilizando a célula de leitura de dados abaixo.
"""

from google.colab import files

uploaded = files.upload()

nome_arquivo = list(uploaded.keys())[0]
print(nome_arquivo)

df = pd.read_csv(
    nome_arquivo,
    sep=';',
    encoding='latin1',
    low_memory=False
)

df.shape

df.head()

"""**1 - Exploração dos Dados**"""

df.columns.tolist()

df.columns

[col for col in df.columns if "NT" in col]

df.columns.tolist()[:40]

len(df.columns)

df.columns.tolist()[:30]

colunas = [
    "NT_GER",
    "NT_FG",
    "TP_PRES",
    "NU_ITEM_OFG",
    "NU_ITEM_OCE"
]

df_sel = df[colunas].copy()

df_sel = df_sel.dropna(subset=["NT_GER"])
df_sel.describe()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure()
sns.histplot(df_sel["NT_GER"], bins=30)
plt.title("Distribuição da Nota Geral do ENADE (2021)")
plt.show()

plt.figure()
sns.scatterplot(x="NT_FG", y="NT_GER", data=df_sel)
plt.title("Relação entre Nota de Formação Geral e Nota Geral")
plt.show()

"""**2 - Perguntas de Pesquisa**


1 - Qual é o grau de associação entre a nota de Formação Geral e a Nota Geral do ENADE?

2 - O desempenho em Formação Geral explica uma parcela significativa da variabilidade da Nota Geral?

3 - A quantidade de itens objetivos de Formação Geral está associada a variações significativas na Nota Geral do ENADE?

4 - A quantidade de itens do Componente Específico contribui de forma independente para o desempenho final, após controlar pela Formação Geral?

5 - A presença do estudante na prova está associada a diferenças significativas na Nota Geral do ENADE?

**3 -  Teste de hipótese com regressão**
"""

import statsmodels.api as sm

X = df_sel[["NT_FG", "TP_PRES", "NU_ITEM_OFG", "NU_ITEM_OCE"]]
y = df_sel["NT_GER"]

X = sm.add_constant(X)

modelo = sm.OLS(y, X).fit()
print(modelo.summary())

"""**4 - Documentação **




Os dados utilizados neste trabalho correspondem aos microdados de desempenho do Exame Nacional de Desempenho dos Estudantes (ENADE) referentes ao ano de 2021, disponibilizados pelo INEP em formato texto delimitado por ponto e vírgula. A etapa inicial consistiu na correta identificação e carregamento do arquivo apropriado dentro do conjunto de microdados, uma vez que o ENADE disponibiliza múltiplos arquivos com diferentes níveis de agregação e finalidades distintas.

Após o carregamento da base, foi realizada uma inspeção exploratória da estrutura dos dados, incluindo a verificação do número de registros, variáveis disponíveis e tipos de dados. Essa etapa revelou que o conjunto analisado contém predominantemente informações relacionadas ao desempenho dos estudantes e à estrutura da prova, não incluindo variáveis socioeconômicas ou institucionais, o que orientou o escopo da análise.

Em função dessa característica da base, optou-se por direcionar a investigação para a relação entre os componentes da avaliação (Formação Geral, Componente Específico e presença na prova e a Nota Geral do ENADE). Foi realizada uma limpeza mínima dos dados, removendo registros sem informação de nota geral, de modo a garantir a consistência das análises sem descaracterizar a base original.

A etapa de exploração dos dados envolveu análises estatísticas descritivas e visualizações gráficas, como histogramas e gráficos de dispersão, com o objetivo de compreender a distribuição das notas e identificar possíveis padrões e relações entre variáveis. Essas análises exploratórias subsidiaram a formulação das perguntas de pesquisa e da hipótese central do estudo.

Para o teste da hipótese, foi ajustado um modelo de regressão linear múltipla, tendo a Nota Geral do ENADE como variável dependente , como variáveis explicativas, a Nota de Formação Geral, a presença do estudante na prova e indicadores relacionados à quantidade de itens objetivos da avaliação. O modelo permitiu avaliar a contribuição individual de cada componente da prova para o desempenho final.

Por fim, ressalta-se que os resultados obtidos devem ser interpretados à luz das limitações da base analisada. A ausência de variáveis socioeconômicas, institucionais e contextuais impede inferências causais mais amplas sobre o desempenho dos estudantes, restringindo a análise a associações estatísticas. Ainda assim, o estudo demonstra um processo analítico consistente e reproduzível, evidenciando a capacidade de adaptação metodológica frente às restrições impostas pelos dados disponíveis.
"""